export const API_POKEMON= 'https://pokeapi.co/api/v2/pokemon';
export const SEND_REQUEST='SEND_REQUEST';
export const REQUEST_SUCCESS= 'REQUEST_SUCCESS';
export const REQUEST_FAILURE= 'REQUEST_FAILURE';
export const REQUEST_LOADING= 'REQUEST_LOADING';
export const GET_STUDENTS = 'GET_STUDENTS';
export const RUTAQUEGABIAUNNOMEPASA = 'RUTAQUEGABIAUNNOMEPASA';
export const GET_STUDENTS_SUCESS = 'GET_STUDENTS_SUCESS';
export const GET_STUDENTS_FAILURE = 'GET_STUDENTS_FAILURE';
export const GET_STUDENTS_AZ = 'GET_STUDENTS_AZ';
export const GET_STUDENTS_ZA = 'GET_STUDENTS_ZA';
export const GET_STUDENTS_HIGH_SCORE = 'GET_STUDENTS_HIGH_SCORE';
export const GET_PUBLIC_FOLLOWS = 'GET_PUBLIC_FOLLOWS';
export const GET_PUBLIC_FOLLOWS_SUCESS = 'GET_PUBLIC_FOLLOWS_SUCESS';
export const SET_REGISTER_TRUE = 'SET_REGISTER_TRUE'; // despues hay que borrarla 
export const GET_INFO_USER_SUCCES = 'GET_INFO_USER_SUCCES';
export const SET_REGISTER_TRUE_SUCCES = 'SET_REGISTER_TRUE_SUCCES';
export const POST_USER_FAILURE = 'POST_USER_FAILURE';
export const VACIAR_ESTADO = 'VACIAR_ESTADO';

export const GET_PUBLICATIONS_BUSINESS = 'GET_PUBLICATIONS_BUSINESS'; 
export const GET_PUBLICATIONS_BUSINESS_SUCCESS = 'GET_PUBLICATIONS_BUSINESS_SUCCESS';
export const URL_PEDIDO = "http://henryjob.herokuapp.com/api" // reemplazar por la ruta de pedidos de publicaciones de empresas
export const URL_PEDIDO_POSTS = "http://henryjob.herokuapp.com/api/post"
export const GET_PUBLICATIONS_TECHNOLOGIES = "GET_PUBLICATIONS_TECHNOLOGIES";
export const GET_PUBLICATIONS_DEVTYPE = "GET_PUBLICATIONS_DEVTYPE";
export const GET_PUBLICATIONS_ENGLISH = "GET_PUBLICATIONS_ENGLISH";
export const GET_PUBLICATIONS_WORK_MODALITY = "GET_PUBLICATIONS_WORK_MODALITY";
export const GET_PUBLICATIONS_UBICATION = "GET_PUBLICATIONS_UBICATION";

export const GET_PUBLICATION_STUDENTS = "GET_PUBLICATION_STUDENTS";
export const GET_PUBLICATION_STUDENTS_SUCCESS = "GET_PUBLICATION_STUDENTS_SUCCESS";
export const GET_PUBLICAT_TECHNOLOGIES = "GET_PUBLICAT_TECHNOLOGIES";
export const GET_PUBLICAT_ENGLISH = "GET_PUBLICAT_ENGLISH";
export const GET_PUBLICAT_WORKMODALITY = "GET_PUBLICAT_WORKMODALITY";
export const GET_PUBLICAT_UBICATION = "GET_PUBLICAT_UBICATION";
export const GET_PUBLICAT_DEVTYPE = "GET_PUBLICAT_DEVTYPE";

export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";

export const URL_PEDIDO_USER = "URL_PEDIDO_USER"; // URL QUE TRAE INFO DE USUARIO
export const GET_INFO_USER = "GET_INFO_USER";
export const GET_INFO_USER_SUCCESS = "GET_INFO_USER_SUCCESS";
export const ACTUALIZAR_ESTADO = "ACTUALIZAR_ESTADO";
export const SEND_EMAIL_CONTACT = "SEND_EMAIL_CONTACT";
export const ACTUALIZAR_HOME_BUSINESS = "ACTUALIZAR_HOME_BUSINESS";
export const PUNTUAR = "PUNTUAR";
export const REINICIAR_PERFIL = "REINICIAR_PERFIL";
export const REINICIAR_HOME_PRINCIPE = "REINICIAR_HOME_PRINCIPE";



export const POST_USER= 'POST_USER';
export const POST_USER_SUCCESS='POST_USER_SUCCESS';
export const URL_POST='http://henryjob.herokuapp.com/api/signin';

export const HENRY_LOGO ='https://blog.soyhenry.com/content/images/2021/03/151211491_440151970756357_8005198803636550092_o.jpg';
export const SHOW_FILTER = "SHOW_FILTER";
export const SET_STARS_ORDER = "SET_STARS_ORDER";

export const GET_INFO_FOR_STAFF = "GET_INFO_FOR_STAFF";
export const GET_INFO_FOR_STAFF_SUCCESS = "GET_INFO_FOR_STAFF_SUCCESS";
export const GET_STUDENT_DETAIL = "GET_STUDENT_DETAIL";
export const STAFF_ORDER_STUDENTS = "STAFF_ORDER_STUDENTS";
export const STAFF_SHOW_ORDER = "STAFF_SHOW_ORDER";
export const SET_LOGOUT='SET_LOGOUT';

export const POST_ID_FOLLOW = 'POST_ID_FOLLOW';
export const POST_ID_FOLLOW_SUCCESS = 'POST_ID_FOLLOW_SUCCESS';
export const POST_ID_FOLLOW_BUSS = 'POST_ID_FOLLOW_BUSS';
export const POST_ID_FOLLOW_BUSS_SUCCESS = 'POST_ID_FOLLOW_BUSS_SUCCESS';


export const URL_DEPLOY = 'http://henryjob.herokuapp.com/api';
export const NEW_GET_INFO_USER = 'NEW_GET_INFO_USER';
export const NEW_GET_INFO_USER_SUCCESS = 'NEW_GET_INFO_USER_SUCCESS';


export const PROFILE_SUCCESS= 'PROFILE_SUCCESS';
export const PROFILE_ID='PROFILE_ID';

export const URL_PROFILE= 'http://henryjob.herokuapp.com/api/user/';

export const POST_REGISTER_MODAL = "POST_REGISTER_MODAL";
export const POST_REGISTER_MODAL_SUCCESS = "POST_REGISTER_MODAL_SUCCESS";
export const SET_USERTYPE = "SET_USERTYPE";
export const SET_DEV_TYPE_AND_TECH = "SET_DEV_TYPE_AND_TECH";
export const SET_LOCATION_ENG_STUDY = "SET_LOCATION_ENG_STUDY";
export const SET_RECRUITER_INFO = "SET_RECRUITER_INFO";
export const SET_BUSINESS_INFO = "SET_BUSINESS_INFO";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const GET_MY_PUBLICATIONS = "GET_MY_PUBLICATIONS";
export const GET_MY_PUBLICATIONS_SUCCESS = 'GET_MY_PUBLICATIONS_SUCCESS';
export const SET_APPLICANT = "SET_APPLICANT";
export const GET_BUSINESS_BY_EMAIL = "GET_BUSINESS_BY_EMAIL";
export const GET_BUSINESS_BY_EMAIL_SUCCESS = "GET_BUSINESS_BY_EMAIL_SUCCESS";
export const GET_STUDENTS_BY_EMAIL = "GET_BUSINESS_BY_EMAIL";
export const GET_STUDENTS_BY_EMAIL_SUCCESS = "GET_BUSINESS_BY_EMAIL_SUCCESS";
export const SEND_NUDES = "SEND_NUDES";
export const SEND_NUDE_SUCCESS = "SEND_NUDE_SUCCESS";
export const POSTULARSE = "POSTULARSE";
export const GET_MY_APPLICAT_SUCCESS = "GET_MY_APPLICAT_SUCCESS";
export const GET_MY_APPLICAT = "GET_MY_APPLICAT";
export const POST_PUBLICATION_STU = "POST_PUBLICATION_STU";
export const BUGG_NAV = "BUGG_NAV";
export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";

export const GET_PREMIUM_BUSINESS = "GET_PREMIUM_BUSINESS";
export const GET_PREMIUM_BUSINESS_SUCCESS = "GET_PREMIUM_BUSINESS_SUCCESS";
export const SET_PREMIUM = "SET_PREMIUM";
export const SET_GOOGLE_USER = "SET_GOOGLE_USER";
export const USER_DELETE = "USER_DELETE";
export const TRAER_FOLLOWING = "TRAER_FOLLOWING";
export const TRAER_FOLLOWING_SUCCESS = "TRAER_FOLLOWING_SUCCESS";
export const TRAER_FOLLOWING_STUD = "TRAER_FOLLOWING_STUD";
export const TRAER_FOLLOWING_STUD_SUCCESS = "TRAER_FOLLOWING_STUD_SUCCESS";
export const BORRAR_PUBLICACIONES = "BORRAR_PUBLICACIONES";
export const SEND_EMAIL = "SEND_EMAIL";
export const EMAIL_EXISTE = "EMAIL_EXISTE";
export const EMAIL_EXISTE_SUCCESS = "EMAIL_EXISTE_SUCCESS";

export const EDIT_PROFILE= 'EDIT_PROFILE';
export const PROFILE_EDIT_URL='http://henryjob.herokuapp.com/api/user/';
export const SET_BUSBUSQUEDA='SET_BUSBUSQUEDA';


